cargo-features = ["strip"]

[package]
name = "isar-core-dart-ffi"
version = "0.0.0"
authors = ["Simon Leier <simonleier@gmail.com>"]
edition = "2021"

[dependencies]
isar-core = { path = "../" }
threadpool = "1.8.1"
once_cell = "1.7.1"
serde_json = "1.0.64"
byteorder = "1"
enum-ordinalize = "3.1.8"

[lib]
crate-type=["staticlib", "cdylib"]

[profile.release]
lto = true
codegen-units = 1
strip = "symbols"